### ISSUE TITLE
Things go into Offline mode and dont recover on temporary connectivity issues

### ISSUE THREAD

**Issue by martink2** [dfrommi/openhab-tado#9]
Hi @dfrommi,

thanks a lot for this tado implementation for openhab. I have been using
the plugin for a couple of months now and observed something strange:

When temporary connectivity problems occur like DSL disconnects or router 
reboots in my home some of my Things go into the following state:

![image](https://user-images.githubusercontent.com/1143193/40766337-6fe9f756-64af-11e8-9cbd-b9d108e94bcf.png)

This by itself would not be an issue since the thing is actually offline but unfortunately 
they never recover until i restart the openhab server after which it immediately works again.

I am unfortunately neither a great Java specialist nor a very experienced OpenHAB user,
so if you could give me a pointer on how to further debug the issue in more detail that would 
be greatly appreciated. Is there for example a way to set the plugin into debug LOG ?

Thanks

Martin

**Comment by dfrommi** [comment]
Hi @martink2 

Thanks for the interest in the tado binding. Hope you like it.

This binding is now part of OpenHAB and will be available out of the box in OpenHAB 2.3. As part of the integration, some improvements were done.
Could you please verify it again when 2.3 is out and see if the issue is still there? And if so, please raise an issue in the openhab2-addons repo.

**Comment by dfrommi** [comment]
Moved to official openhab addon repo: https://github.com/openhab/openhab2-addons/issues/3628
